import Head from 'next/head';
import React from 'react';

const signUp = () => {
  return (
    <div>
      <Head>
        <title>Speech || Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>This is Sign Up Page</h2>
    </div>
  );
};

export default signUp;
