import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import { FiUser } from 'react-icons/fi';
import { MdAlternateEmail, MdPassword } from 'react-icons/md';
import { TbUserPlus } from 'react-icons/tb';
import Button from '../components/Button';
import Input from '../components/Input';
import AuthLayout from '../layout/AuthLayout';
import styles from '../styles/auth.module.scss';

const SignUp = () => {
  const [formData, setFormData] = useState();

  const handleChange = ({ target }) =>
    setFormData({ ...formData, [target.name]: target.value });

  const handleRegister = async () => {
    console.log({ formData });
  };

  return (
    <AuthLayout>
      <Head>
        <title>Speech || Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={styles.auth_form}>
        <div>
          <h1>Register</h1>
          <p>You and your friends always connected.</p>
        </div>

        <Input
          placeholder="Enter your name"
          label="Name"
          name="name"
          prefix={<FiUser />}
          onChange={handleChange}
        />

        <Input
          placeholder="Enter your Email"
          type="email"
          label="Email"
          name="email"
          prefix={<MdAlternateEmail />}
          onChange={handleChange}
        />

        <Input
          placeholder="Enter Your Password"
          name="password"
          label="Password"
          type="password"
          prefix={<MdPassword />}
          onChange={handleChange}
        />

        <Input
          placeholder="Should Match with password"
          name="confirm_password"
          label="Confirm Password"
          type="password"
          prefix={<MdPassword />}
          onChange={handleChange}
        />

        <Button
          label="Sign Up"
          type="button"
          icon={<TbUserPlus />}
          onClick={handleRegister}
        />

        <p>
          Already have an account ? <Link href="/signIn">Login</Link>
        </p>
      </form>
    </AuthLayout>
  );
};

export default SignUp;
