import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import { FiUser } from 'react-icons/fi';
import { MdAlternateEmail, MdPassword } from 'react-icons/md';
import { TbUserPlus } from 'react-icons/tb';
import Button from '../components/Button';
import Input from '../components/Input';
import AuthLayout from '../layout/AuthLayout';
import styles from '../styles/auth.module.scss';

const SignUp = () => {
  const [formData, setFormData] = useState({});
  const [errors, setErrors] = useState();

  const handleChange = ({ target }) => {
    setFormData({ ...formData, [target.name]: target.value });
  };

  // console.log(formData);

  const handleRegister = (e) => {
    e.preventDefault();
    console.log(formData);
  };

  return (
    <AuthLayout>
      <Head>
        <title>Speech || Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={styles.auth_form} onSubmit={handleRegister}>
        <div>
          <h1>Register</h1>
          <p>You and your friends always connected.</p>
        </div>

        <Input
          placeholder="Enter your name"
          label="Name"
          name="name"
          prefix={<FiUser />}
          onChange={handleChange}
          validation={/^[A-Z]+/}
        />

        <Input
          placeholder="Enter your Email"
          type="email"
          label="Email"
          name="email"
          prefix={<MdAlternateEmail />}
          onChange={handleChange}
          validation={/^[A-Za-z0-9_.+-]+@[a-zA-Z]+\.[a-z]+/}
        />

        <Input
          placeholder="Enter Your Password"
          name="password"
          label="Password"
          type="password"
          prefix={<MdPassword />}
          onChange={handleChange}
          validation={/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}$/}
        />

        <Input
          placeholder="Should Match with password"
          name="confirm_password"
          label="Confirm Password"
          type="password"
          prefix={<MdPassword />}
          onChange={handleChange}
          validation={new RegExp(formData.password)}
        />

        <div>
          <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike" />
          <label htmlFor="vehicle1">I have a bike</label>
        </div>

        <Button
          label="Sign Up"
          type="submit"
          disabled
          icon={<TbUserPlus />}
          // onClick={handleRegister}
        />

        <p>
          Already have an account ? <Link href="/signIn">Login</Link>
        </p>
      </form>
    </AuthLayout>
  );
};

const validation = (data) => {
  console.log(data);
};

export default SignUp;
