/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { BiLogIn } from 'react-icons/bi';
import { FiUser } from 'react-icons/fi';
import { MdPassword } from 'react-icons/md';
import Button from '../components/Button';
import Input from '../components/Input';
import AuthLayout from '../layout/AuthLayout';
import styles from '../styles/auth.module.scss';

const signIn = () => {
  return (
    <AuthLayout>
      <Head>
        <title>Speech || Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className={styles.auth_form}>
        <div>
          <h1>Login</h1>
          <p>You and your friends always connected.</p>
        </div>

        <Input
          placeholder="Enter your Email"
          label="Email"
          name="email"
          prefix={<FiUser />}
        />
        <Input
          placeholder="Enter your Password"
          label="Password"
          name="password"
          type="password"
          prefix={<MdPassword />}
        />

        <Button label="Sign In" type="button" icon={<BiLogIn />} />

        <p>
          Don't have account ? <Link href="/signUp">Register</Link>
        </p>
      </form>
    </AuthLayout>
  );
};

export default signIn;
