import Head from 'next/head';
import React from 'react';

const signIn = () => {
  return (
    <div>
      <Head>
        <title>Speech || Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>This is Sign In page</h2>
    </div>
  );
};

export default signIn;
