import Head from 'next/head';
import React from 'react';
import Button from '../components/Button';
import AuthLayout from '../layout/AuthLayout';
import styles from '../styles/auth.module.scss';

const Verify = () => {
  return (
    <AuthLayout>
      <Head>
        <title>Speech || Verify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.auth_form}>
        <h1>Verification</h1>
        <h2>Thank you for registration.</h2>
        <p>
          To start exploring the Speech app, please verify your email address.
          We will send you a verification code to your email.
        </p>
        <Button label="Send Code" />
      </div>
    </AuthLayout>
  );
};

export default Verify;
